[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Using Change Management Communication to Inform Corporate Social Responsibility Initiatives: Addressing Environmental and Social Issues"
